name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Echo out a GitHub Actions Secret to the logs
      run: |
        echo "The GitHub Action Secret will be masked:  "
        echo ${{ env.MAC_ENV}}
        echo ${{ secrets.MAC_REPO}}
        echo "Trick to echo GitHub Actions Secret:  "
        echo ${{env.MAC_ENV}} | sed 's/./& /g'
        echo ${{secrets.MAC_REPO}} | sed 's/./& /g'
    - name: Set env as secret
      env:
        MY_VAL: ${{ env.MAC_ENV }}
      run: |
        import os
        for q in (os.getenv("MY_VAL")):
          print(q)
      shell: python

