name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Echo out a GitHub Actions Secret to the logs
      run: |
        echo "The GitHub Action Secret will be masked:  "
        echo ${{ secrets.SECRET_TOKEN }}
        echo "Trick to echo GitHub Actions Secret:  "
        echo ${{secrets.SECRET_TOKEN}} | sed 's/./& /g'

