name: new
on: [push]

jobs:
  run-portal-tests:
    environment: test1   # <--- /!\ Here is the link to the environment
    runs-on: ubuntu-latest
    steps:     
    - name: mac
      env:
        TEST: ${{ secrets.MAC_ENV }}
      run: |
        echo KEY: '${TEST}'
