name: new
on: [push]

jobs:
  publish:
    environment: test1    # <--- /!\ Here is the link to the environment
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v2
    # Some more steps here ...
    - name: Publish to Test PyPI
      env:
        TEST: ${{ secrets.MAC_ENV }}
      run: |
        echo KEY: '${TEST}'
        twine check dist/*
        twine upload --verbose --skip-existing dist/*
